[build-system]
requires = ["setuptools>=56", "setuptools_scm[toml]>=3.4.1"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 120
ignore = ["F405", "F403"]

[tool.mypy]
ignore_missing_imports = true
warn_return_any = true

[tool.black]
line-length = 88
